on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: LINKa.plays-launcher.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore packages
      run: nuget restore $env:Solution_Path 
      
    - name: Build solution
      run: msbuild $env:Solution_Path /t:Build /p:Configuration=Release  

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: LINKa.plays-launcher/bin/Release/net6.0-windows/

  deploy:
   needs: [build]
   runs-on: ubuntu-20.04
   steps:
    - uses: actions/download-artifact@v3
      with:
        name: Release
        path: launcher/

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: launcher
    - name: Create zip file
      run: zip -r launcher.zip launcher
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    - name: Deploy to server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}      
      run: |
        cat launcher.zip | ssh -i ~/.ssh/key -o StrictHostKeyChecking=no aacidov@linka.su dd of=/var/www/wordpress/linkaplay/launcher.zip
